[package]
name = "usbd-mass-storage"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4.17"

usb-device = {git = "https://github.com/betrusted-io/usb-device.git", branch = "main"}
